export const EVENTS_CLEAR_LIST = 'EVENTS_CLEAR_LIST';
export const EVENTS_DELETE_EVENT = 'EVENTS_DELETE_EVENT';
export const EVENTS_FILTER_EVENTS = 'EVENTS_FILTER_EVENTS';

export const EVENTS_NAME_CHANGED = 'EVENTS_NAME_CHANGED';
export const EVENTS_WHERE_CHANGED = 'EVENTS_WHERE_CHANGED';
export const EVENTS_DATE_CHANGED = 'EVENTS_DATE_CHANGED';
export const EVENTS_HOUR_CHANGED = 'EVENTS_HOUR_CHANGED';
