export const EVENTS_GET_EVENTS = 'EVENTS_GET_EVENTS';
export const EVENTS_GET_EVENTS_SUCCESS = 'EVENTS_GET_EVENTS_SUCCESS';
export const EVENTS_GET_EVENTS_ERROR = 'EVENTS_GET_EVENTS_ERROR';

export const EVENTS_CLEAR_LIST = 'EVENTS_CLEAR_LIST';
export const EVENTS_DELETE_EVENT = 'EVENTS_DELETE_EVENT';
export const EVENTS_FILTER_EVENTS = 'EVENTS_FILTER_EVENTS';

export const EVENTS_NAME_CHANGED = 'EVENTS_NAME_CHANGED';
export const EVENTS_WHERE_CHANGED = 'EVENTS_WHERE_CHANGED';
export const EVENTS_DATE_CHANGED = 'EVENTS_DATE_CHANGED';
export const EVENTS_HOUR_CHANGED = 'EVENTS_HOUR_CHANGED';

export const EVENTS_ADD_EVENT = 'EVENTS_ADD_EVENT';

export const DETAILS_GET_DETAILS = 'DETAILS_GET_DETAILS';
export const DETAILS_GET_DETAILS_SUCCESS = 'DETAILS_GET_DETAILS_SUCCESS';
export const DETAILS_GET_DETAILS_ERROR = 'DETAILS_GET_DETAILS_ERROR';

export const DETAILS_SELECT_EVENT = 'DETAILS_SELECT_EVENT';
